name: cron job

on:
  #Triggers workflow every minute
  schedule:
  - cron: "30,00 * * * *"
  
jobs:
  cron:
    runs-on: ubuntu-20.04
    steps:
      - name: shcmd
        run: go run ./cmd/main.go
